apiVersion: pingcap.com/v1alpha1
kind: TidbMonitor
metadata:
  name: monitor
  namespace: csn
spec:
  persistent: true
  storageClassName: shared-sas-disks
  storage: 20G
  clusters:
    - name: my-test
      namespace: csn
  prometheus:
    baseImage: prom/prometheus
    version: v2.18.1
    service:
      type: NodePort
  grafana:
    baseImage: grafana/grafana
    version: "9.0.1"
    service:
      type: NodePort
  initializer:
    baseImage: pingcap/tidb-monitor-initializer
    version: v6.1.0
  reloader:
    baseImage: pingcap/tidb-monitor-reloader
    version: v1.0.1
  imagePullPolicy: IfNotPresent
