apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: my-test
  namespace: csn
spec:
  version: latest
  timezone: UTC
  enableTLSCluster: false
  pvReclaimPolicy: Delete
  enableAdvertiseAddress: true
  autoFailover: false
  configUpdateStrategy: RollingUpdate
  pd:
    baseImage: hub-new.pingcap.net/csn/pd
    version: multi-tenant-3320891
    replicas: 1
    service:
      type: NodePort
    storageClassName: pd-nvme-disks
    limits:
      cpu: 4000m
      memory: 8Gi
    requests:
      cpu: 4000m
      memory: 8Gi
      storage: 200Gi
    config:
      log:
        level: "info"
        file:
          filename: /var/log/pdlog/pd.log
      dashboard:
        enable-telemetry: false
        enable-experimental: true
    storageVolumes:
      - name: log
        storageClassName: shared-sas-disks
        storageSize: "20Gi"
        mountPath: "/var/log/pdlog"
  tikv:
    env:
      - name: TEST_TIKV_TAGS
        value: "test_need_restart"
    baseImage: hub-new.pingcap.net/csn/tikv
    version: multi-tenant-1-69937fb
    replicas: 3
    storageClassName: nvme-disks
    maxFailoverCount: 0
    evictLeaderTimeout: 1h
    limits:
      cpu: 8000m
      memory: 20Gi
      storage: 500Gi
    requests:
      cpu: 8000m
      memory: 20Gi
      storage: 500Gi
    storageVolumes:
      - name: log
        storageClassName: shared-sas-disks
        storageSize: "20Gi"
        mountPath: "/var/log/tikvlog"
    config: |
      log-level = "info"
      log-file = "/var/log/tikvlog/tikv.log"
      status-addr = "0.0.0.0:20180"

  tidb:
    baseImage: hub.pingcap.net/csn/tidb
    version: multi-tenants-n2-f851dae
    replicas: 2
    maxFailoverCount: 0
    enableAdvertiseAddress: true
    service:
      type: ClusterIP
    storageClassName: shared-sas-disks
    limits:
      cpu: 8000m
      memory: 16Gi
    requests:
      cpu: 8000m
      memory: 16Gi
    config: |
      token-limit = 1000000
      [prepared-plan-cache]
        enabled = true
      [log]
        level = "info"
      [log.file]
        filename = "/var/log/tidblog/tidb.log"
    storageVolumes:
      - name: log
        storageClassName: shared-sas-disks
        storageSize: "20Gi"
        mountPath: "/var/log/tidblog"
